spring:
  jpa:
    hibernate:
      ddl-auto: "update"
  datasource:
    url: "jdbc:mysql://localhost:3306/aslet"
    username: "root"
    password: ""
    driver-class-name: "com.mysql.cj.jdbc.Driver"